<Settings>:
    orientation: 'vertical'

<VScodePath>:
    size_hint_y: None
    orientation: 'vertical'
    Label:
        text:'VScode'
        size_hint_y: None
        height: dp(48)
        padding: dp(8), 0, 0, 0  # Убираем отступы
        halign: 'left'  # Выравнивание текста по левому краю
        text_size: self.size  # Устанавливаем размер текста равным размеру Label
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(48)
        padding: dp(8)
        spacing: dp(4)
        TextInput:
            id: user_input
            multiline: False
            hint_text: 'Введите путь к файлу VScode...'
            size_hint_x: 1

        Button:
            text: 'PATH'
            size_hint_x: None
            width: dp(80)
            on_release: root.select_path()

<BrowserPath>:
    size_hint_y: None
    orientation: 'vertical'
    Label:
        text:'Browser'
        size_hint_y: None
        height: dp(48)
        padding: dp(8), 0, 0, 0  # Убираем отступы
        halign: 'left'  # Выравнивание текста по левому краю
        text_size: self.size  # Устанавливаем размер текста равным размеру Label
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: dp(48)
        padding: dp(8)
        spacing: dp(4)
        TextInput:
            id: user_input
            multiline: False
            hint_text: 'Введите путь к файлу браузера...'
            size_hint_x: 1

        Button:
            text: 'PATH'
            size_hint_x: None
            width: dp(80)
            on_release: root.select_path()

<ConfirmSettings>:
    size_hint_y: None
    BoxLayout:
        orientation: 'horizontal'
        padding: 8
        Widget: 
            size_hint_x: 1
        Button:
            text: 'Confirm'
            size_hint_x: None
            size_hint_y: None
            width: dp(80)
            height: dp(35)
            on_release: root.confirm()
        