<Settings>:
    AnchorLayout:
        anchor_x: 'center'      # по горизонтали центр
        anchor_y: 'center'      # по вертикали центр
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(48)
            padding: dp(8)
            spacing: dp(4)

            TextInput:
                id: user_input
                multiline: False
                hint_text: 'Введите путь...'
                size_hint_x: 1

            Button:
                text: 'PATH'
                size_hint_x: None
                width: dp(80)
                on_release: root.select_path()
        Widget: